WebShop/Areas/Admin/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shop.DataAccess.Repository;
using Shop.Models;
using Shop.Utility;

namespace WebShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles =SD.Role_Admin)]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<Company> companies = _unitOfWork.Companies.GetAll();

            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new Company());
        }
        [HttpPost]
        public IActionResult Create(Company company)
        {
            if (!ModelState.IsValid)
            {
                TempData["failure"] = "Please, input valid field data";
                return View(company);
            }
            _unitOfWork.Companies.Add(company);
            _unitOfWork.Complete();
            TempData["success"] = "Successfully created company";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            Company company = _unitOfWork.Companies.Find(u => u.Id == id);
            if (company == null)
            {
                return NotFound();
            }
            return View(company);
        }
        [HttpPost]
        public IActionResult Edit(Company company)
        {
            if(!ModelState.IsValid) {
                TempData["failure"] = "Please, input valid field data";
                return View(company);
            }
            _unitOfWork.Companies.Update(company);
            _unitOfWork.Complete();
            TempData["success"] = "Successfully edited company";
            return RedirectToAction("Index");   
        }
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            Company company = _unitOfWork.Companies.Find(u => u.Id == id);
            if (company == null)
            {
                return NotFound();
            }
            return View(company);
        }
        [HttpPost]
        public IActionResult Delete(Company company)
        {
            _unitOfWork.Companies.Delete(company);
            _unitOfWork.Complete();
            TempData["success"] = "Successfully deleted company";
            return RedirectToAction("Index");
        }



        #region APICALLS 
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Company> companies = _unitOfWork.Companies.GetAll().ToList();
            return Json(new {data = companies });
        }
        #endregion

    }
}

WebShop/Areas/Customer/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.ValueGeneration.Internal;
using Shop.DataAccess.Repository;
using Shop.Models;
using Shop.Models.ViewModels;
using Shop.Utility;
using Stripe.BillingPortal;
using Stripe.Checkout;
using System.Security.Claims;

namespace WebShop.Areas.Customer.Controllers
{
	[Area("Customer")]
	[Authorize]
	public class ShoppingCartController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		[BindProperty]
		public ShoppingCartVM shoppingCartVM { get; set; }
		public ShoppingCartController(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}
		public IActionResult Index()
		{

			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

			var items = _unitOfWork.ShoppingCarts.GetAll(includeProperties: "Product").Where(cart => cart.ApplicationUserId == userId).ToList();
			decimal total = (decimal)items?.Sum(item => item.Count * item.Product.Price);

			shoppingCartVM = new ShoppingCartVM()
			{
				Items = items,
				OrderHeader = new OrderHeader() { OrderTotal = total }
			};

			return View(shoppingCartVM);
		}
		public IActionResult IncrementProduct(int productId)
		{
			ShoppingCart cart = _unitOfWork.ShoppingCarts.Find(cart => cart.ProductId == productId);
			cart.Count++;
			_unitOfWork.ShoppingCarts.Update(cart);
			_unitOfWork.Complete();
			return RedirectToAction(nameof(Index));
		}
		public IActionResult DecrementProduct(int productId)
		{
			ShoppingCart cart = _unitOfWork.ShoppingCarts.Find(cart => cart.ProductId == productId);
			cart.Count--;
			if (cart.Count == 0)
			{
				_unitOfWork.ShoppingCarts.Delete(cart);
			} else
			{
				_unitOfWork.ShoppingCarts.Update(cart);
			}
			_unitOfWork.Complete();
			return RedirectToAction(nameof(Index));
		}
		public IActionResult RemoveProduct(int productId)
		{
			ShoppingCart cart = _unitOfWork.ShoppingCarts.Find(cart => cart.ProductId == productId);
			_unitOfWork.ShoppingCarts.Delete(cart);
			_unitOfWork.Complete();
			return RedirectToAction(nameof(Index));
		}
		public IActionResult Summary()
		{

			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

			var items = _unitOfWork.ShoppingCarts.GetAll(includeProperties: "Product").Where(cart => cart.ApplicationUserId == userId).ToList();
			decimal total = (decimal)items?.Sum(item => item.Count * item.Product.Price);

			var user = _unitOfWork.ApplicationUsers.Find(u => u.Id == userId);

			shoppingCartVM = new ShoppingCartVM()
			{
				Items = items,
				OrderHeader = new OrderHeader()
				{
					OrderTotal = total,
					ApplicationUser = user,
					PhoneNumber = user.PhoneNumber,
					PostalCode = user.PostalCode,
					State = user.State,
					City = user.City,
					StreetAddress = user.StreetAddress,
					Name = user.Name
				}
			};

			return View(shoppingCartVM);
		}

		[HttpPost]
		[ActionName("Summary")]
		public IActionResult SummaryPOST()
		{

			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

			var items = _unitOfWork.ShoppingCarts.GetAll(includeProperties: "Product").Where(cart => cart.ApplicationUserId == userId).ToList();
			decimal total = (decimal)items?.Sum(item => item.Count * item.Product.Price);

			var user = _unitOfWork.ApplicationUsers.Find(u => u.Id == userId);

			shoppingCartVM.OrderHeader.ShippingDate = DateTime.Now;

			shoppingCartVM.OrderHeader.ApplicationUserId = userId;
			shoppingCartVM.Items = items;

			bool customerIsRegular = user.CompanyId.GetValueOrDefault() == 0;


			if (customerIsRegular)
			{
				shoppingCartVM.OrderHeader.PaymentStatus = "Pending";
				shoppingCartVM.OrderHeader.OrderStatus = "Pending";
			} else
			{
				shoppingCartVM.OrderHeader.PaymentStatus = "DelayedPayment";
				shoppingCartVM.OrderHeader.OrderStatus = "Approved";
			}
			_unitOfWork.OrderHeaders.Add(shoppingCartVM.OrderHeader);
			_unitOfWork.Complete();
			foreach (var item in shoppingCartVM.Items)
			{
				OrderDetail orderDetail = new OrderDetail
				{
					ProductId = item.ProductId,
					Price = item.Product.Price,
					Count = item.Count,
					OrderHeaderId = shoppingCartVM.OrderHeader.Id
				};
				_unitOfWork.OrderDetails.Add(orderDetail);
				_unitOfWork.Complete();
			}


			if (customerIsRegular)
			{
				var domain = "https://localhost:7232/";
				var options = new Stripe.Checkout.SessionCreateOptions
				{

					SuccessUrl = $"{domain}customer/shoppingcart/OrderConfirmation?id={shoppingCartVM.OrderHeader.Id}",
					CancelUrl = $"{domain}customer/shoppingcart/index",
					LineItems = new List<SessionLineItemOptions>(),
					Mode="payment"
					
				}; 

				foreach(var item in shoppingCartVM.Items)
				{
					SessionLineItemOptions sessionLineItem = new()
					{
						PriceData = new SessionLineItemPriceDataOptions()
						{
							UnitAmount = (long)(item.Product.Price * 100),
							Currency = "rub",
							ProductData = new SessionLineItemPriceDataProductDataOptions()
							{
								Name = item.Product.Name
							}

						},
						Quantity = item.Count
					};
					options.LineItems.Add(sessionLineItem);
				}

				var service = new Stripe.Checkout.SessionService();
				Stripe.Checkout.Session session= service.Create(options);
				_unitOfWork.OrderHeaders.UpdateStripePaymentId(shoppingCartVM.OrderHeader.Id, session.Id, session.PaymentIntentId);
				_unitOfWork.Complete();
				Response.Headers.Add("Location", session.Url);
				return new StatusCodeResult(303);
			}

			return RedirectToAction(nameof(OrderConfirmation), new { id = shoppingCartVM.OrderHeader.Id });
		}
		public IActionResult OrderConfirmation(int id)
		{
			return View();
		}

	}
}

WebShop/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.DataAccess.Data;
using Shop.DataAccess.Repository;
using Shop.Models;


namespace WebShop.Controllers
{
    public class CategoryController : Controller
    {
        private readonly UnitOfWork unitOfWork;
        public CategoryController(ApplicationDbContext dbContext)
        {
                unitOfWork = new UnitOfWork(dbContext);
        }
        public IActionResult Index()
        {
            List<Category> categories = unitOfWork.Categories.GetAll().ToList();
            return View(categories);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Category obj)
        {
            if (ModelState.IsValid) { 
                unitOfWork.Categories.Add(obj);
                unitOfWork.Complete();
                TempData["failure"] = "Category created successfully";
                return RedirectToAction("Index");
            }
            TempData["failure"] = "Wrong field data! Try again";
            return View();
        }
        public IActionResult Edit(int id)
        {
            if (id==null || id == 0){
                return NotFound();
            }
            Category? categoryFromDb = unitOfWork.Categories.Get(id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }
        [HttpPost]
        public IActionResult Edit(Category obj)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.Categories.Update(obj);
                unitOfWork.Complete();
                TempData["success"] = "Category edited successfully";
                return RedirectToAction("Index");
            }
            TempData["failure"] = "Wrong field data! Try again";
            return View();
        }
        public IActionResult Delete(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category? categoryFromDb = unitOfWork.Categories.Get(id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }
            
            return View(categoryFromDb);
        }
        [HttpPost]
        public IActionResult Delete(Category obj)
        {
            unitOfWork.Categories.Delete(obj);
            unitOfWork.Complete();
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("Index");
        }


    }
}

WebShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap_flatly.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebShop.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <script src="https://cdn.tiny.cloud/1/waud7nense3dtvycyj3mpuadf5ukpxrgs5hdb5flvtmmmo3w/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ShoppingCart" asp-action="Index">Shopping Cart</a>
                        </li>
                        @if(User.IsInRole(SD.Role_Admin)){
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Category" asp-action="Index">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Product" asp-action="Index">Products</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Company" asp-action="Index">Companies</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js">
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebShop/Views/Shared/_Notification.cshtml
@{
    if(TempData["success"] != null)
    {
        <script src="/lib/jquery/dist/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <script type="text/javascript">
            toastr.success("@TempData["success"]");
        </script>
    }
    if (TempData["failure"] != null)
    {
        <script src="/lib/jquery/dist/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <script type="text/javascript">
            toastr.success("@TempData["failure"]");
        </script>
    }
}

WebShop/Views/Shared/_Notifications.cshtml
@{
    if (TempData["success"] != null)
    {
        <h2>Success</h2>
    }
    if (TempData["failure"] != null)
    {
        <h2>failure</h2>
    }
}

WebShop/Views/Shared/_tinyMceTextArea.cshtml
<script>
        tinymce.init({
            selector: 'textarea',
            plugins: 'autolink image link lists media searchreplace table visualblocks wordcount checklist mediaembed casechange pageembed editimage tableofcontents powerpaste tinymcespellchecker autocorrect a11ychecker typography inlinecss',
            toolbar: 'undo redo | align lineheight | tinycomments | checklist numlist bullist indent outdent | removeformat',
            tinycomments_mode: 'embedded',
            tinycomments_author: 'Author name',
            mergetags_list: [
                { value: 'First.Name', title: 'First Name' },
                { value: 'Email', title: 'Email' },
            ],
            ai_request: (request, respondWith) => respondWith.string(() => Promise.reject("See docs to implement AI Assistant")),
        });
</script>